//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "users")]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  #[sea_orm(unique)]
  pub uid: Option<i32>,
  #[sea_orm(column_type = "Text", unique)]
  pub name: String,
  #[sea_orm(column_type = "Text", unique)]
  pub email: String,
  #[sea_orm(column_type = "Text")]
  pub passwd: String,
  pub created_at: Option<DateTimeWithTimeZone>,
  pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
#[allow(dead_code)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
